/*CRIANDO BANCO*/

CREATE DATABASE PROJETO;

/*USAR A BASE DE DADOS*/

USE PROJETO;

/* CRIAR A TABELA */

CREATE TABLE CLIENTE(
    nome VARCHAR(30),
    sexo CHAR(1),
    email VARCHAR(30),
    cpf INT(11),
    telefone VARCHAR(30),
    endereco VARCHAR(100)
);

/* VERIFICANDO AS TABELAS DO CAMPO */

SHOW TABLES;

/* DESCOBRINDO COMO É A ESTRUTURA DE UMA TABELA */
DESC CLIENTE;